### ISSUE TITLE
Case with integrity attribute specified

### ISSUE THREAD

**Issue by XhmikosR** [filamentgroup/loadCSS#204] opened 2017-01-21 09:48 UTC
From https://html.spec.whatwg.org/multipage/semantics.html#attr-link-integrity:

>The integrity attribute represents the integrity metadata for requests which this element is responsible for. The value is text. The attribute must not be specified on link elements that do not have a rel attribute that contains the stylesheet keyword. [SRI]

So, how can one still use this but be spec compliant?

TIA

/CC @sideshowbarker @scottjehl

**Comment by scottjehl** [comment] 2017-02-13 22:12
Closing as dupe of #106

**Closed by scottjehl** 2017-02-13 22:12 UTC
