### ISSUE TITLE
Firefox: Duplicating css loading

### ISSUE THREAD

**Issue by Mudin** [filamentgroup/loadCSS#189] opened 2016-10-07 02:50 UTC
Hello,

Thanks for great function!
I have an issue. It is loading my .css files twice.
and it is sill there in google page speed insight.

![screen shot 2016-10-07 at 11 49 28 am](https://cloud.githubusercontent.com/assets/15241252/19177435/25e01f82-8c84-11e6-8dc1-1b75175d1eec.png)

Thank you

Best regards

Mudin

**Comment by rsteinwand** [comment] 2016-10-07 12:13
Is this your problem? https://github.com/filamentgroup/loadCSS/issues/110

**Comment by rsteinwand** [comment] 2016-10-07 13:34
You should be able to test here, using Chrome and other browsers, then check waterfall: https://www.webpagetest.org/

**Comment by kwoxer** [comment] 2016-12-19 12:22
I have the same issue. I'm using Firefox on Ubuntu. Both are latest.

Also I'm using Firefox and also Firefox Dev. I have the same issue in both browser.

This is what my `html.tpl` looks like:
```
<script>
    /*! loadCSS: ... */
...
    /*! preoadCSS: ... */
...
  </script>
  <link rel="preload" href="/sites/all/themes/.../css/main.css" as="style" onload="this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="/sites/all/themes/.../css/main.css"></noscript>
  <style>
```
this works great in **Chrome**. It is loading the main.css via lazy loading. And also after a reload the `main.css` is still cached.

This issue is with **Firefox**/Dev. Here the main.css is somehow loaded 2 times but with a different size (unzipped). Here is a pic: http://i.imgur.com/7MDcpAM.png

So why is Firefox not loading the `main.css` from the Cache after the first visit? And why Firefox is loading the main.css 2 times?

This makes no sense for me because in Chrome it works perfectly well!

Thanks for any idea.

**Comment by scottjehl** [comment] 2017-02-13 21:46
Latest demo link is here for testing this issue: https://master-origin-loadcss.fgview.com/test/preload.html

**Comment by scottjehl** [comment] 2017-02-13 21:54
I'm seeing double-loading in Firefox.

**Comment by MarcoHengstenberg** [comment] 2017-02-14 08:43
On the latest demo `slow.css.php` is requested four times in Firefox (Mac OSX El Capitan, Firefox 51.0.1). 😨

**Comment by scottjehl** [comment] 2017-02-14 14:22
I'll be looking at this today.

**Comment by scottjehl** [comment] 2017-02-14 14:44
@MarcoHengstenberg I'm not seeing this issue today in Firefox, same version and platform. 

Can you double check this https://master-origin-loadcss.fgview.com/test/preload.html

Here's what I see every time:


![image](https://cloud.githubusercontent.com/assets/214783/22933651/d85ec672-f291-11e6-9c0d-56be0b7d4b66.png)

**Comment by MarcoHengstenberg** [comment] 2017-02-14 16:09
@scottjehl Just fired up the page again and lo and behold: there are only two requests for the file now, the second starting right after the first has completed.

![loadcss-firefox-doublerequest](https://cloud.githubusercontent.com/assets/3168733/22937237/47f86e84-f2d8-11e6-85a8-9212b9550bc9.png)

**Comment by scottjehl** [comment] 2017-02-14 17:37
Hmm. I can't seem to reproduce the problem anymore.  It's just one request every time I try now.

@MarcoHengstenberg can you hover hover the Cause column to see the trace for which JS lines trigger the second request? For example:

![image](https://cloud.githubusercontent.com/assets/214783/22941138/ecfff8fe-f2a9-11e6-9bc0-95bc485c0476.png)

**Comment by MarcoHengstenberg** [comment] 2017-02-15 07:40
Morning @scottjehl Find attached a screenshot of the issue :)
The screenshot is made from hovering over the cause column of the second request.

![loadcss-firefox-trace](https://cloud.githubusercontent.com/assets/3168733/22964725/56025f94-f35a-11e6-91ec-f25303d64754.png)

Hope this helps.

**Comment by scottjehl** [comment] 2017-02-15 14:22
Interesting. I'm not sure what to make of that trace.

@miketaylr might you have a moment to try and reproduce this one? [This test page](https://master-origin-loadcss.fgview.com/test/preload.html) uses `link[rel=preload]` to reference a stylesheet, and in Firefox our loadCSS script polyfills support for that attribute by fetching the stylesheet with `loadCSS()`. It should only make one request, but some folks are seeing two. I can't reproduce, as shown here https://github.com/filamentgroup/loadCSS/issues/189#issuecomment-279778498

**Comment by miketaylr** [comment] 2017-02-15 22:36
I only see the single request... testing in 53 (DevEdition) and 54 (Nightly).

<img width="1920" alt="screen shot 2017-02-15 at 4 34 48 pm" src="https://cloud.githubusercontent.com/assets/67283/22998525/bd756e4a-f39c-11e6-937e-f7dce76e5e1c.png">

@MarcoHengstenberg which platform are you on, and which version are you seeing the double request in?

**Comment by MarcoHengstenberg** [comment] 2017-02-16 16:18
@miketaylr Firefox (Mac OSX El Capitan, Firefox 51.0.1)

Retesting now… same result.

![loadcss-firefox-trace-02](https://cloud.githubusercontent.com/assets/3168733/23029799/fd04e124-f46b-11e6-834c-bfc26f3bd0ae.png)

**Comment by miketaylr** [comment] 2017-02-16 17:50
Thanks for re-testing @MarcoHengstenberg! 

Does the same bug reproduce in Nightly or Dev Edition (downloads here: https://www.mozilla.org/en-US/firefox/channel/desktop/)

**Comment by MarcoHengstenberg** [comment] 2017-02-16 19:08
I'll try tomorrow. =) Family-time now.

**Comment by MarcoHengstenberg** [comment] 2017-02-17 07:30
Now, this is getting weird.
Firefox Nightly 54.0a1 is behaving the exact same way. I guess I'll try and mute a few add-ons and see whether there's something going on here.

![loadcss-firefoxnightly-trace-02](https://cloud.githubusercontent.com/assets/3168733/23056339/e25f8fd2-f4e2-11e6-87a6-7f719c464fae.png)

**Comment by MarcoHengstenberg** [comment] 2017-02-17 07:38
Alright then. I think I found the issue and it's with my setup.

I had the "HTTP-Cache disabled when devTools is open" flag enabled and as I went and unticked it the behaviour of the preload testpage's been as expected.

I re-disabled the HTTP-Cache then and reloaded the page and it's still working. No second request. Goes for Firefox Nightly and current (51.0.1).

**Comment by scottjehl** [comment] 2017-02-17 15:20
Thanks folks. Closing out!

**Closed by scottjehl** 2017-02-17 15:20 UTC

**Comment by miketaylr** [comment] 2017-02-17 16:08
> Alright then. I think I found the issue and it's with my setup.

Thanks for taking the time to figure this out, @MarcoHengstenberg!

**Comment by MarcoHengstenberg** [comment] 2017-02-22 16:59
Sure @miketaylr 
I'm using loadCSS in almost every project currently, so contributing (in whatever way) seems natural to me. =)
