### ISSUE TITLE
Does not work with rangeslider.js

### ISSUE THREAD

**Issue by jenstornell** [filamentgroup/loadCSS#96] opened 2015-09-04 07:44 UTC
It worked for most part but it did not work with http://andreruffert.github.io/rangeslider.js/. I tried the callback solution but it still didn't work.

Maybe it has to do with callback fire too early, hard for me to say.

**Comment by scottjehl** [comment] 2015-09-30 02:57
Just so I'm clear, are you trying to run this script via our onloadCSS callback function? Thanks.

**Comment by scottjehl** [comment] 2016-01-27 21:19
Closing this out as a dupe of #74

**Closed by scottjehl** 2016-01-27 21:19 UTC
