### ISSUE TITLE
IE 8 behaviour

### ISSUE THREAD

**Issue by superpoincare** [filamentgroup/loadCSS#112] opened 2015-11-20 07:26 UTC
I am getting a strange behaviour in IE8 and below. 

The script seems to load the CSS fine in the first load.

But in the second load, this happens (see screenshot): onloadcssdefined = "..." appears in the link element. 

![loadcss ie8](https://cloud.githubusercontent.com/assets/13736892/11294042/1eb6033a-8f86-11e5-8835-75d05b2bf040.png)

Not only that, but IE8 seems to be using css/styles inside @media print { ... } to display the page!

(Have disabled loadCSS for IE8 and older after getting this bug, so can't check this live.)

**Comment by superpoincare** [comment] 2015-11-23 04:55
I solved this by using Modernir's CSS media queries build and also modifying loadCSS a bit: I set media to all and inject css if Modernizr.mq('only all') is false. Else I let loadCSS behave as usual. It's fine because old browsers render block anyway. Ideally I need something small (and no conditional IE comments). If someone knows a simple media query JS smaller than Modernizr's CSS media queries please let me know. My aim was to simplify everything and just have inline css and loadCSS(...) which I achieved.

**Comment by rsteinwand** [comment] 2016-04-22 20:37
I'm seeing the same behavior, and only in IE8. IE9 and other browsers work just fine so had to quickly roll back to my previous script, which doesn't seem to work as well.

I don't need or use Modernizr so would like to see this fixed properly. I haven't fully tested, but I think passing "all" to the media type parameter may fix it.

**Comment by scottjehl** [comment] 2017-02-13 22:03
reopened. So this issue occurs when the loaded stylesheet contains a `@media print` block?

**Comment by vijayaraghavanramanan** [comment] 2017-02-14 16:09
Hi @scottjehl 

Yes, it occurs when it contains a `@media print ` block and the browser (IE8 and less) uses the styles from this.

**Comment by rsteinwand** [comment] 2017-12-01 13:50
I can confirm this is still an issue with v2, but only if there's a @media print block in the post-loaded css.

The problem is the post-loaded print section is applied to screen. 

Since IE9 and below don't support TLS1.2 and we block everything else, this isn't an issue for us and I'm unable to post a test case. (ie9 and below can't access our site)

Considering how IE8 doesn't natively support media queries in the first place, I doubt this will ever be fixed. As far as I'm concerned, this case could be closed.

**Comment by rsteinwand** [comment] 2017-12-01 14:42
That said, this is also an issue if compatibility mode is enabled, which I'll bug separately.

**Comment by rasenplanscher** [comment] 2019-03-04 06:39
I could not reproduce this in Microsoft's IE8-VM with `preload.html` from this repository.
Therefore, I recommend closing this @scottjehl

**Comment by rasenplanscher** [comment] 2019-03-21 08:24
Additionally, the `loadCSS` does not support IE8 anymore, because it uses `addEventListener` without `attachEvent` fallback.

**Closed** 2022-10-20 20:28 UTC
