### ISSUE TITLE
Doesn't render when return the previous page on iOS Safari.

### ISSUE THREAD

**Issue by nakoo** [filamentgroup/loadCSS#71] opened 2015-06-07 06:09 UTC
Doesn't render loadCSS when return the previous page on iOS Safari. I think the problem is occurred for browser cache. Can I get to prevent the page from browser cache?

**Comment by scottjehl** [comment] 2015-06-09 13:37
Can you post a little of the code you're using to call `loadCSS`?

**Comment by nakoo** [comment] 2015-06-09 14:36
I'm just using loadCSS.js which be minified. loadCSS function are called to be in js file for asynchronous.
It's same as follow unless some of them above.

**Comment by scottjehl** [comment] 2015-06-09 15:14
I've set up a test directory to try to reproduce this. https://github.com/filamentgroup/loadCSS/tree/71/test/71

There are 2 pages, one.html, and two.html. One.html uses loadCSS to load a CSS file, `test.css`, which styles the `body` element's background color green. The screencast below shows me:
1. opening one.html (green background means loadCSS worked properly), 
2. clicking a link to two.html
3. clicking the back button to return to one.html (again, green background means loadCSS worked properly)

Based on this, I'm thinking you may be seeing an implementation-specific issue. Closing out because I can't reproduce it, but please let me know if I can change anything with this test to make it reproduce the bug.

![71](https://cloud.githubusercontent.com/assets/214783/8061419/580805b0-0e90-11e5-9bc3-3b5180acc995.gif)

**Closed by scottjehl** 2015-06-09 15:14 UTC

**Comment by nakoo** [comment] 2015-07-11 07:25
I solved the problem. It is caused async attribute. I changed the attribute to defer, which does work well.
