### ISSUE TITLE
loadCSS crashes Firefox 38 and 41

### ISSUE THREAD

**Issue by giratikanon** [filamentgroup/loadCSS#134] opened 2016-02-06 00:09 UTC
Calling `loadCSS` breaks versions 38 and 41 of Firefox, and possibly the versions in between.

Here's a test page that runs `loadCSS`: http://codepen.io/anon/pen/eJPRVP?editors=0010

On [Firefox 41](https://ftp.mozilla.org/pub/firefox/releases/41.0/) on a Mac, loading that URL makes Firefox unresponsive until the program is force quit. Same with Firefox 38.

If you delete the `loadCSS` call on that page, everything works normally.

**Comment by yoyurec** [comment] 2016-02-12 11:15
+1

**Comment by zachleat** [comment] 2016-02-12 14:53
Hm, I can reproduce this successfully in Browserstack on Firefox 41 using jsbin. Here’s the test case:
http://output.jsbin.com/yugame

**Comment by yoyurec** [comment] 2016-02-12 14:57
BTW, **0.2.4** works ok

**Comment by scottjehl** [comment] 2016-02-12 15:00
Good to know.  Thanks for the report @giratikanon @yoyurec 

Maybe it's stuck in some sort of onload handler loop. Let us know if you see anything... we'll get on it.

**Comment by yoyurec** [comment] 2016-02-12 15:14
maybe this can help https://www.mozilla.org/en-US/security/advisories/mfsa2015-135/

**Comment by vijayaraghavanramanan** [comment] 2016-02-12 15:22
Maybe not related, but this [site](http://keithclark.co.uk/articles/loading-css-without-blocking-render/) says that the trick 

`<link rel="stylesheet" href="css.css" media="none" onload="if(media!='all')media='all'">
`

crashes on Firefox.

**Comment by scottjehl** [comment] 2016-02-12 15:25
Thanks @vijayaraghavanramanan 

That approach, while very concise, only works in browsers that have onload support for links. Unfortunately, that's not the case for whole lot of modern androids out there.

**Comment by scottjehl** [comment] 2016-02-12 15:31
@giratikanon also, just anecdotally, we were curious if you ran into this through user reports or just lab testing? Just wondering how prevalent these versions are since FF is evergreen, by default at least. 

If there's something we can do to fix it though, I'm into it.

**Comment by giratikanon** [comment] 2016-02-12 15:37
User reports. Roughly 20% of our Firefox users are at least two versions behind the latest, with version 38 being the most common, for some reason.

**Comment by scottjehl** [comment] 2016-02-12 15:41
Thanks, Tom.

**Comment by vijayaraghavanramanan** [comment] 2016-02-12 15:45
@giratikanon that's because Firefox supports 38 ESR for organizations. 

https://www.mozilla.org/en-US/firefox/organizations/faq/

**Comment by yoyurec** [comment] 2016-02-12 16:01
> we were curious if you ran into this through user reports
user reports, lot of people are using 38 here ))

**Comment by miketaylr** [comment] 2016-02-12 16:05
Has anyone successfully submitted a crash report after reproducing the bug?

If you can give the me the crash IDs, that would be helpful (check about:crashes)

**Comment by yoyurec** [comment] 2016-02-12 16:08
sorry, no logs ((
using Browserstack, so it crashes and new instance is empty

**Comment by vijayaraghavanramanan** [comment] 2016-02-12 16:12
@scott this chart explains 38's prevalence (from Mozilla's site)
![release-overview 2ba45c58671a](https://cloud.githubusercontent.com/assets/13736892/13012480/73d4134c-d1d1-11e5-9c5b-2a1f9da2d905.png)

**Comment by miketaylr** [comment] 2016-02-12 16:14
> sorry, no logs ((

No worries, I'm trying to bisect this with http://mozilla.github.io/mozregression/, let's see if I can find something.

**Comment by miketaylr** [comment] 2016-02-12 16:46
OK, using `mozregression --find-fix -b 38 -g 46`, I got it down to https://hg.mozilla.org/integration/mozilla-inbound/pushloghtml?fromchange=c25738e63a8214a44628df16f1c406eff9d8824c&tochange=e4f18dacf879ddce2043f9dca77af3d39c968f23.

That's from https://bugzilla.mozilla.org/show_bug.cgi?id=1203973, which given the title of "Changing media in onload= in <link> hangs Firefox" feels like the right bug fix. 

What that does mean is before Firefox 44, this probably will hang or crash browsers, probably going back before 38 :(

**Comment by scottjehl** [comment] 2016-02-12 16:50
well that is helpful and unfortunate! Thanks Mike. 

Moving the media toggle to onload really helped us with a few issues in other browsers, like preventing occasional double-requests in Chrome. 

We'll give this some thought now. Thanks again

**Comment by bzbarsky** [comment] 2016-02-12 18:02
The simplest thing to do is probably to just set a flag on your element when changing the media value so you don't respond to the load event the media change will end up firing...

**Comment by scottjehl** [comment] 2016-03-02 19:10
Quick update: looks like toggling media via a setTimeout lets the stack clear or whatever and prevents this bug in 41 and 38. I'll post a PR shortly. Testing for any regressions elsewhere first (double-downloads in Chrome could be one thing to watch out for).

**Comment by scottjehl** [comment] 2016-03-02 22:51
Another update!

So it turns out that a workaround we added last release, as an attempt to stop Chrome from occasionally requesting a CSS file twice, is not working 100% of the time in further testing. This workaround also happens to be what introduced this old-firefox crash: we started using an onload handler (where supported) to toggle the link's media type. 

I've reopened the bug for the double-request in Chrome https://github.com/filamentgroup/loadCSS/issues/110#issuecomment-191464973 and since I'm able to reproduce it with a few simple steps independent of loadCSS, I made a reduced test case (linked in that comment) to see if the Chrome team thinks its worth fixing or if perhaps there's a workaround we can try.

For loadCSS, I think we should remove the onload handler in loadcss.js and go back to toggling the media via our original check (which didn't require onload and thus didn't crash old Firefox).

As for Chrome, I think we're in good shape there anyway because the momentum of this project is very much heading in the direction of using loadCSS merely as a polyfill for browsers that don't understand `link[rel=preload]`, which brings us native asynchronous CSS loading. Chrome will soon have `preload` support in stable, so loadCSS won't need to run in that browser anyway, and this bug won't matter much. If you're interested, here's a demo of that pattern, which we'll be recommending as the primary means of loading async CSS: http://filamentgroup.github.io/loadCSS/test/preload.html

A caveat: after we remove onload for the toggle, we'll be re-introducing an issue with our onloadCSS.js extension, fixed with last release, which could cause it to fire its "onload" callback before the media attribute was toggled. To retain the fix, I think we'll need to poll the media attribute in that handler and make sure it has been toggled before allowing the onload callback to fire.

For anyone affected by this bug right now, I'd recommend rolling back to loadCSS `0.2.2` if you aren't relying on the onloadCSS handler. 

We'll get this settled in the next release. + @giratikanon

**Comment by scottjehl** [comment] 2016-03-03 22:37
@giratikanon turns out the fix was simpler than it seemed.

Mind testing this? https://github.com/filamentgroup/loadCSS/pull/143

We may merge it sooner... I've got FF 41 running tests without crashing now. Thanks!

**Comment by vijayaraghavanramanan** [comment] 2016-03-04 14:46
I am getting a cannot change media of undefined. 

Sorry no test site as I rolled back.

**Comment by scottjehl** [comment] 2016-03-04 14:50
I'm getting that now too. Thanks. On it...

**Comment by scottjehl** [comment] 2016-03-04 16:02
Okay, all tests are passing and FF 41's no longer crashing.

I'll merge this in a few. https://github.com/filamentgroup/loadCSS/pull/143

**Closed** 2016-03-04 16:30 UTC
Labels: bug
