### ISSUE TITLE
Microsoft Edge loads CSS twice

### ISSUE THREAD

**Issue by bjoe2k4** [filamentgroup/loadCSS#222] opened 2017-04-26 18:59 UTC
Observed on Windows 10 1703 and Microsoft Edge with Demo site.

![grafik](https://cloud.githubusercontent.com/assets/1668390/25451630/225111a4-2ac3-11e7-99a3-1a6fe7fb0fa5.png)

**Comment by scottjehl** [comment] 2017-06-06 21:28
hmm. yeah I can confirm. It's seemingly not a loadCSS issue so much as a media attribute toggling issue. Edge reports a new css fetch if you toggle the media attribute. This is a common scenario we've also seen in Chrome (before preload was implemented) and sometimes in Firefox too.

Here's a simple test page that shows the two requests just from a link element that starts as `media=none` and becomes `media=all` when it loads:
https://basic-onload-toggle-origin-loadcss.fgview.com/test/basiconloadtoggle.html

In my opinion, the best way to mitigate this problem is to ensure you have good expires and caching settings on your CSS so that when it's fetched again, it 304s instead of making a network request.

Since we've tried to fix this one for other browsers in the past and eventually filed bugs with the browsers themselves instead of addressing it here, I'm going to close this out as wont-fix. 

Thanks!

**Closed by scottjehl** 2017-06-06 21:28 UTC
