### ISSUE TITLE
Firefox Doesn't Execute Preload CSS Rules

### ISSUE THREAD

**Issue by thealkimist** [filamentgroup/loadCSS#246] opened 2017-11-09 22:21 UTC
Hi all,

We've been trying to integrate critical CSS into our project, and based on previous tickets, (#189, #177), Firefox issues still persist in another form. The critical CSS seems to have rendered our project inoperable on Firefox (56.0.2). Here is our snippet:

MacOS Sierra
Firefox 56.0.2

```
      <script>
      /*! loadCSS. [c]2017 Filament Group, Inc. MIT License */
      !function(a){"use strict";var b=function(b,c,d){function e(a){return h.body?a():void setTimeout(function(){e(a)})}function f(){i.addEventListener&&i.removeEventListener("load",f),i.media=d||"all"}var g,h=a.document,i=h.createElement("link");if(c)g=c;else{var j=(h.body||h.getElementsByTagName("head")[0]).childNodes;g=j[j.length-1]}var k=h.styleSheets;i.rel="stylesheet",i.href=b,i.media="only x",e(function(){g.parentNode.insertBefore(i,c?g:g.nextSibling)});var l=function(a){for(var b=i.href,c=k.length;c--;)if(k[c].href===b)return a();setTimeout(function(){l(a)})};return i.addEventListener&&i.addEventListener("load",f),i.onloadcssdefined=l,l(f),i};"undefined"!=typeof exports?exports.loadCSS=b:a.loadCSS=b}("undefined"!=typeof global?global:this);
      /*! loadCSS rel=preload polyfill. [c]2017 Filament Group, Inc. MIT License */
      !function(a){if(a.loadCSS){var b=loadCSS.relpreload={};if(b.support=function(){try{return a.document.createElement("link").relList.supports("preload")}catch(b){return!1}},b.poly=function(){for(var b=a.document.getElementsByTagName("link"),c=0;c<b.length;c++){var d=b[c];"preload"===d.rel&&"style"===d.getAttribute("as")&&(a.loadCSS(d.href,d,d.getAttribute("media")),d.rel=null)}},!b.support()){b.poly();var c=a.setInterval(b.poly,300);a.addEventListener&&a.addEventListener("load",function(){b.poly(),a.clearInterval(c)}),a.attachEvent&&a.attachEvent("onload",function(){a.clearInterval(c)})}}}(this);
      </script>
      <style type="text/css">
         @charset "UTF-8";body,div{margin:0;padding:0}a,body{color:#0a0a0a}html{font-family:sans-serif;line-height:1.15;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}header{display:block}svg:not(:root){overflow:hidden}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}html{box-sizing:border-box;font-size:100%}*,::after,::before{box-sizing:inherit}body{background:#fefefe;font-family:Lato;font-weight:400;line-height:1.5;-webkit-font-smoothing:antialiased;-moz-osx-font-smoothing:grayscale}a{background-color:transparent;-webkit-text-decoration-skip:objects;line-height:inherit;text-decoration:none}
      </style>
      <link rel="preload" href="/sites/all/themes/current_theme/assets/css/app.css?1510258544" as="style" onload="this.rel='stylesheet'">
      <noscript><link rel="stylesheet" href="/sites/all/themes/current_theme/assets/css/app.css?1510258544"></noscript>
      <script></script><!-- here to ensure a non-blocking load still occurs in IE and Edge, even if scripts follow loadCSS in head -->
```

We also noticed that running https://master-origin-loadcss.fgview.com/test/preload.html on Firefox, though successfully fetches `slow.css.php`, never executes the rules as well.

![firefox preload issue](https://user-images.githubusercontent.com/2328144/32632242-7b00bc1a-c568-11e7-8e0c-c19d77bb4b75.png)

**Comment by scottjehl** [comment] 2017-11-09 22:35
So, the issue with this is, I believe, the same as reported in other issues: Firefox 56 will not fire an `onload` event on a `rel=preload` link if the requested resource is not deemed "cacheable" by Firefox. 

Our test page's stylesheet has cache-control headers set so that the cache expires immediately, so it is hit by this Firefox bug, which will be gone (by way of disabling preload support entirely) in Firefox 57.

![image](https://user-images.githubusercontent.com/214783/32633017-6e3d4edc-c56b-11e7-81ea-8ad783b5e70b.png)

Here's an example of a site where `preload` still works in Firefox because its CSS is cacheable: https://www.filamentgroup.com/ 

The options I know of for this are to a) configure you headers to allow caching in Firefox, or b) add an `onerror="this.rel='stylesheet'"` attribute to the link, since Firefox will still call the `onerror` event. I'd recommend `a` if possible.

If your issue appears to be different from this, let me know! Thanks.
Closing as a duplicate of https://github.com/filamentgroup/loadCSS/issues/237

**Closed by scottjehl** 2017-11-09 22:35 UTC

**Comment by thealkimist** [comment] 2017-11-10 15:49
@scottjehl, thanks Scott. Apologies for the dupe.

**Comment by scottjehl** [comment] 2017-11-10 15:50
@thealkimist hey no prob. I thought it was a new bug when I read it. This stuff is complicated!
