### ISSUE TITLE
Preload pattern not working in chrome 49

### ISSUE THREAD

**Issue by clambelet** [filamentgroup/loadCSS#154] opened 2016-03-11 11:35 UTC
The test page for Async CSS w/ link[rel=preload] is not working in Chrome 49 (only tested on os x).
The stylesheet is retrieved by the browser but not applied to the page.

![cap 2016-03-11 a 12 34 16](https://cloud.githubusercontent.com/assets/17782289/13701086/9d707a14-e785-11e5-8f58-2208b4ef756a.jpg)

**Comment by scottjehl** [comment] 2016-03-11 14:05
Hmm. Seems okay for me. Chrome 49 does not pass the feature test so the css is still fetched via JS. Image verifies:

![image](https://cloud.githubusercontent.com/assets/214783/13704087/b778c7f2-e75f-11e5-9f77-ad44bafa02e1.png)

Do you have experimental flags enabled perhaps? I do believe there's a bug with the experimental preload handling (it looks for `stylesheet` rather than `style`) but it is fixed in Canary, so that'll land without a problem when it makes it into stable.

Closing as can't reproduce but... let me know what you find!

**Closed by scottjehl** 2016-03-11 14:05 UTC

**Comment by clambelet** [comment] 2016-03-11 14:15
Thanks, it was indeed a flag :)
