### ISSUE TITLE
Chrome Bug (to be fixed by Chrome team): loadCSS creates two requests for one css file in Chrome

### ISSUE THREAD

**Issue by HouCoder** [filamentgroup/loadCSS#110] opened 2015-10-30 16:02 UTC
The loadCSS function creates two requests for one css file, it only happens in Chrome, I tested the latest Chrome on OS X and Windows 7, they both have this problem, seems because the loadCSS changed the `media` attribute's value to `all` caused this problem. I'm not sure it's loadCSS's problem or not, maybe it's Chrome's bug.

This testing link is broken: <del>Here is my testing demo: http://tonni.info/demos/loading-css-asynchronously/</del>

This is a Chromium bug, @scottjehl has reported to Chromium dev team: https://bugs.chromium.org/p/chromium/issues/detail?id=591654

**Comment by scottjehl** [comment] 2015-10-30 16:14
When this issue comes up, it's almost always due to the CSS file not having a future-dated expires header, so it doesn't get cached.  Can you check if you have your caching headers set on your CSS file? Thanks

**Comment by HouCoder** [comment] 2015-10-30 16:26
@scottjehl Thanks for your response, I'm requesting this css file: http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css

It has the caching setting in the response header.

And here is the HTTP request&response detail:

![image](https://cloud.githubusercontent.com/assets/5292143/10851361/ac43abca-7f65-11e5-8af4-d0c75844c4e6.png)

Thanks ;-)

**Comment by scottjehl** [comment] 2015-10-30 16:31
Okay yeah, that makes sense then.

This header has a past date so the browser will fetch a new copy whenever it's requested again:
![image](https://cloud.githubusercontent.com/assets/214783/10851532/9ae33bc8-7ef9-11e5-892f-950a993a48fd.png)

Maybe cdnjs can look at this issue? Something like bootstrap should be able to have some far-future caching I'd think.

**Comment by scottjehl** [comment] 2015-10-30 16:46
updated ^

**Comment by scottjehl** [comment] 2015-10-30 16:56
Just making notes. I only see one request when calling the following from filamentgroup.com:

`loadCSS(" //cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css")`

**Comment by scottjehl** [comment] 2015-10-30 16:58
Okay, and running that again with the latest version of loadCSS (same version you're using) does in fact produce 2 requests. Thanks. Verified, we'll dig in.

**Comment by HouCoder** [comment] 2015-10-31 02:15
@scottjehl I did some tests in my local too, seems Chrome creates a new request when you changing the  `media` attribute. 

![image](https://cloud.githubusercontent.com/assets/5292143/10861388/4226aa46-7fb8-11e5-9412-349e44dbc6f4.png)

**Comment by mjau-mjau** [comment] 2015-11-03 04:38
+1. This issue is solved though if you change from protocol-relative paths, simply to SSL.

Will load twice:
```//cdn.jsdelivr.net/photoswipe/4.1.0/photoswipe.css```

Will load once, as it's supposed to:
```https://cdn.jsdelivr.net/photoswipe/4.1.0/photoswipe.css```

Although this should be fixed in loadCSS, I suggest you change urls to include SSL protocol, as they are recommending at cdnjs and jsdelivr currently. It's counter-productive having both ssl- and non-ssl versions depending on protocol, as this will negate the benefits of pre-cached files. Therefore, it is recommended to stick with SSL version, which also works fine from non-SSL.

**Comment by mjau-mjau** [comment] 2015-11-03 05:31
+1. CSS files get called twice:

![twice](http://d.pr/i/177OB+)

**Comment by mayankchd** [comment] 2015-11-11 18:22
I don't know why but  Replacing this 	

	var onloadcssdefined = function( cb ){
			var resolvedHref = ss.href;
			var i = sheets.length;
			while( i-- ){
				if( sheets[ i ].href === resolvedHref ){
					return cb();
				}
			}
			setTimeout(function() {
				onloadcssdefined( cb );
			});
		};

		// once loaded, set link's media back to `all` so that the stylesheet applies once it loads
		ss.onloadcssdefined = onloadcssdefined;
		onloadcssdefined(function() {
			ss.media = media || "all";
		});

By 

    window.setTimeout(function(){ss.media = media || "all"}, 0);
    return ss;

Fixes it for me .

**Comment by robin-drexler** [comment] 2015-11-17 12:05
+1 We're also experiencing this issue. Are there any updates or known workarounds? Thanks. :)

**Comment by scottjehl** [comment] 2015-11-17 14:02
well, a temporary workaround should be to downgrade to version 0.1.7

https://github.com/filamentgroup/loadCSS/releases/tag/0.1.7 <https://github.com/filamentgroup/loadCSS/releases/tag/0.1.7>

**Comment by robin-drexler** [comment] 2015-11-17 15:16
@scottjehl thanks for the fast reply. :)
Could you please elaborate on why the older version does not cause the multiple requests? As far as I understood, it's caused by the switch of the media attribute. This is done in the older version as well.

**Comment by scottjehl** [comment] 2015-11-17 16:02
I haven’t gotten to the bottom of it yet, but I’d seen that the issue was introduced since that version, so that’s all I could recommend at the moment. Sorry

**Comment by bramstein** [comment] 2015-11-18 12:43
For what it's worth: I spent some time debugging this, and it turns out loadCSS only loads a stylesheet twice if the "Disable cache" button in the network panel is checked (at least in my case). Once that is disabled, the stylesheet is loaded twice, but the second request is from the cache.

**Comment by romuloinnocencio** [comment] 2015-11-25 16:23
this works fine for me, https://github.com/filamentgroup/loadCSS/issues/108

**Comment by scottjehl** [comment] 2015-11-25 16:43
Sounds like https://github.com/filamentgroup/loadCSS/issues/108 is promising. We'll be taking a look as time allows

**Comment by scottjehl** [comment] 2016-01-25 19:27
After some tinkering this morning, I found that if the media toggle takes place via the link's onload event handler, that does not cause a double request in Chrome. Since the current callback is basically an onload workaround anyway, it won't hurt to bind to both and keep whichever applies the toggle first (onload comes before our simulated onloadcssdefined in Chrome). 

Seems to do the trick. I'll push a PR shortly for review.

**Comment by scottjehl** [comment] 2016-01-25 23:28
Hi all. A PR is submitted for this. Comments on the code changes and whether or not it fixes the issue for you are very welcome. Thanks!

**Comment by skyl** [comment] 2016-02-02 22:19
Still the same problem on master as of right now.

**Comment by scottjehl** [comment] 2016-02-02 22:23
@skyl got an example? Looks okay here to me:

![image](https://cloud.githubusercontent.com/assets/214783/12766395/482bda64-c9c9-11e5-9388-2795b1282dc7.png)

**Comment by skyl** [comment] 2016-02-02 23:01
The second fire comes from the `ss.media = media || "all"` line:

```
		// once loaded, set link's media back to `all` so that the stylesheet applies once it loads
		ss.onloadcssdefined = onloadcssdefined;
		onloadcssdefined(function() {
			ss.media = media || "all";
		});
		return ss;
```

Let me double check and make sure I'm not experiencing PEBKAC.

**Comment by skyl** [comment] 2016-02-02 23:11
I can't make a public example at the moment. But, I've definitely got `"version": "1.0.0-0",` everywhere and am experiencing this. Local development server with node ...

Response headers look like this FWIW:

```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Date: Tue, 02 Feb 2016 23:08:31 GMT
Cache-Control: public, max-age=0
Last-Modified: Tue, 02 Feb 2016 21:52:35 GMT
ETag: W/"7e25f-391209796"
Content-Type: text/css; charset=UTF-8
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: keep-alive
Transfer-Encoding: chunked
```

**Comment by scottjehl** [comment] 2016-02-02 23:18
I think your cache control header is causing the browser to request a new version because the file expires on delivery. Seem accurate?

**Comment by skyl** [comment] 2016-02-03 00:22
Tried changing the headers. Same with these:

```
HTTP/1.1 200 OK
Expires: Wed, 01 Feb 2017 22:58:43 GMT
Accept-Ranges: bytes
Date: Wed, 03 Feb 2016 00:22:29 GMT
Cache-Control: public, max-age=31536000
Last-Modified: Tue, 02 Feb 2016 21:52:35 GMT
ETag: W/"7e25f-391209796"
Content-Type: text/css; charset=UTF-8
Vary: Accept-Encoding
Content-Encoding: gzip
Connection: keep-alive
Transfer-Encoding: chunked
```

**Comment by scottjehl** [comment] 2016-02-03 02:12
if you can reproduce in a live demo url I'll be happy to take a look. Thanks

**Comment by skyl** [comment] 2016-02-04 19:23
I wonder what I'm losing if I go with this...

```
function loadCSS(path) {
    var link = document.createElement('link');
    link.type = 'text/css';
    link.rel = 'stylesheet';
    link.href = path;
    document.getElementsByTagName('head')[0].appendChild(link);
}
```

**Comment by scottjehl** [comment] 2016-02-04 21:09
At a glance, 

1. In iOS and Chrome, and IE and Firefox too (I think, but can't recall without testing), your dynamically inserted link will block page rendering until it finishes loading. It's essentially the same as having a link in the head of your source to begin with. This behavior is changing in browsers like Chrome currently, but it's still all over the place across browsers.
2. In older IE, appending to `head` like that can cause it to crash if `head` hasn't fully loaded yet. InsertBefore is considered the safer approach.

The purpose of loadCSS's logic is to insert the link in a way that it'll fetch asynchronously, yet still apply when it's loaded. Modern browsers will fetch any stylesheet in a non-blocking manner if its media type does not match (for example, media=print doesn't block rendering), so that's why loadCSS starts with a non-applicable media attribute, then toggles it to the one you want after the request is at least in flight (or fully loaded).

**Comment by scottjehl** [comment] 2016-03-02 22:29
Reopening this as it is still not fixed in latest, contrary to earlier test results.

A reduced test case demonstrating the behavior in Chrome is here: http://filamentgroup.github.io/loadCSS/test/110-reducedexample.html

![image](https://cloud.githubusercontent.com/assets/214783/13477656/11680f80-e093-11e5-8ded-052cf2b11647.png)

It sometimes takes a few refreshes to see the behavior, as it's inconsistent.

**Comment by mjau-mjau** [comment] 2016-03-03 04:22
Just reference, I can't reproduce this issue in chrome, no matter how many times I refresh or hard-refresh:
![screen](http://d.pr/i/1j76A+)

Latest release definitely fixes the issue for us, as opposed to my post in this thread on Nov 3, 2015.
![screen](http://d.pr/i/1fbD5+)

**Comment by HouCoder** [comment] 2016-03-03 06:54
HTML code error:

![image](https://cloud.githubusercontent.com/assets/5292143/13486872/cef8ab06-e14f-11e5-87a0-296662c07d71.png)

**Comment by scottjehl** [comment] 2016-03-03 13:43
@mjau-mjau thanks. it's a hard one to reproduce, I agree. The chrome team has verified a reduced test case today here: https://bugs.chromium.org/p/chromium/issues/detail?id=591654

**Comment by kofifus** [comment] 2016-03-18 08:13
I'm seeing this as well. Is there any thoughts on resolving this ?

**Comment by dtjones** [comment] 2016-03-18 12:45
Quick question why do you have to wait until onload to change the `media` attribute? wouldn't this still be non-blocking? 

    ready( function(){
        //inserted with media="only x"
        ref.parentNode.insertBefore( ss, ( before ? ref : ref.nextSibling ) );
        // stylesheet starts to download
        // now change media attr
         ss.media = media || "all";
    });

**Comment by englishextra** [comment] 2016-03-21 02:54
https://developers.google.com/speed/pagespeed/insights/

Says I had two identical styles loaded.

**Comment by rsdev000** [comment] 2016-03-21 15:06
Hi

I've got the the same problem: two requests for the css file but only in Chrome. Firefox Dev Edition only shows one request. The headers shows a future expiration date there's must be another problem. A Chtome bug? 

There's also the Pagespeed Insights issue: One CSS blocker resource.

![chrome](https://cloud.githubusercontent.com/assets/9252353/13922919/55a1c618-ef76-11e5-9926-3e94fd6c129e.png)
![firefoxdevedition](https://cloud.githubusercontent.com/assets/9252353/13922920/55ca39f4-ef76-11e5-9b56-b26d9af51725.png)

**Comment by scottjehl** [comment] 2016-03-24 12:50
just to reiterate from above, this is a chrome bug in their tracker. I'll close it out once it's fixed there, but we won't be addressing it here. Thanks
https://bugs.chromium.org/p/chromium/issues/detail?id=591654

**Comment by rsdev000** [comment] 2016-03-25 20:11
@scottjehl 

Thank you very much.

**Comment by JustFly1984** [comment] 2016-04-10 19:27
I'v dig a lot around async assets loading, and I have something to give to community, based on this loadSCC module. It still has a bug with double css loading, which is not bad if you have client caching.
If you have client caching, you need cache invalidation. And here is there everything goes much more complicated. My module works with 3 breaking points (could be extended by fork) -  < 767 || 768 <1199 || 1200 <

It takes an Object, parsed from manifest.json buy your build system, detects client browser for a proper font extension, and runs single callbacks after each css file has been loaded.

It applies a proper css file for each breakpoint, and proper font files to the browser. Now you can forget about huge @fontface rules. - Just provide separate css file for woff || woff2 || svg fonts in base64.

I made this script for my project, and I use Webpack without react.
I found out, that the best way to provide CSS to client - it is separate it to 4 delivery parts.

1st part - is critical CSS or Above the fold CSS and reset.css. Here should be everything to build a layout, and hide everything else, until everything is rendered, fonts applied and so on.
Also this is a great plase to set all your responsive breakpoints for html, like font-size - to set responsive rem sizing.

2nd part - component CSS - BEM like CSS for all your components, either React, either any other inlined, or just required by Webpack., except @media CSS.

3rd part - is responsive @media CSS, which is way overhead to send all in one time. So build a separate css file for each breakpoint, and load it async according to the browser

Please do not judge strong - this is my first give back to community based on this loadCSS module, but with callback, strippers and blackjack.

https://gist.github.com/JustFly1984/8420b137721b76be8f304b3ab43f2dec.

**Comment by scottjehl** [comment] 2016-04-11 12:31
The chrome bug causing this issue has been assigned to a developer so it should be fixed soon. Keep ya posted.

**Comment by sschengyf** [comment] 2016-07-20 01:44
I also encountered this situation, seems only happens on Chrome. I have tested Safari, FF, IE, all fine.

**Comment by scottjehl** [comment] 2016-07-20 12:44
@sschengyf thanks. Just repeating from above, but it's a Chrome bug that the Chrome team has accepted in their tracker. We won't be fixing it here.

**Comment by englishextra** [comment] 2016-07-20 13:05
@sschengyf  That been discussed long ago. Yeah, Google https://developers.google.com/speed/pagespeed/insights/ seems to use and old lib, though latest Chrome Browser (51.0.2704.106 m (64-bit) in my case) loads only once. Correct me if I messed smth here. So the he.. with the Pagespeed.

**Comment by HouCoder** [comment] 2016-07-20 13:11
@scottjehl I updated the description for this issue, I hope it will reduce the notifications from this issue.

**Comment by artursopelnik** [comment] 2016-08-31 08:26
Nice workaround, if you have to optimize "google" pagespeed:
http://keithclark.co.uk/articles/loading-css-without-blocking-render/

**Comment by Fjonan** [comment] 2016-11-30 06:22
I could circumvent the issue by wrapping the loadCSS(...) call into a setTimout. Maybe that is a worthwhile workaround until this is fixed.

**Comment by hummal** [comment] 2016-12-15 16:21
Can not confirm that workaround working on Google Pagespeed Insights

**Comment by scottjehl** [comment] 2016-12-15 16:26
Hi folks. Just so I can confirm: are we now referring to the pagespeed insights warning or the double css loading bug? 

As mentioned in the issue description, the 2-requests issue is a Chrome bug that may be fixed now, though probably not as it's still open: https://bugs.chromium.org/p/chromium/issues/detail?id=591654

**Comment by hummal** [comment] 2016-12-15 16:27
I referring both. 
Still got the double chome request and so does the PSI -> double PSI Chrome request

**Comment by scottjehl** [comment] 2016-12-15 16:30
Sounds like the same Chrome Bug causing both, is that correct?

**Comment by hummal** [comment] 2016-12-15 16:31
Agree!

**Comment by englishextra** [comment] 2016-12-15 16:31
Using loading particular polifill for each device/browser I figured out that Pagespeed loads the following dependencies:

```
…romise/3.2.2/js/es6-promise.fixed.min.js
cdn/fetch/1.0.0/js/fetch.fixed.min.js
cdn/polyfill/0.1.27/js/url.fixed.min.js
…diate/1.0.5/js/setImmediate.fixed.min.js
…l/2.0.0/js/weakmap-polyfill.fixed.min.js
``` 

So now using caniuse 

```
http://caniuse.com/#search=promise
```
you can calculate which android chrome it is.

**Comment by adiie9** [comment] 2017-02-14 16:37
Hi,
I have read the details on this page and seems like it is not Chrome issue.
Check this: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.legalinz.com%2Femployment-law-uae-fixed-fee-services%2F

If you look at "Eliminate render-blocking JavaScript and CSS in above-the-fold content"
You will see only one CSS blocking. (actually there are total 3x requests for CSS files)

But check this page: https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.legalinz.com%2Fsharia-compliant-will%2F

You will see 6x CSS files. 3x CSS files are being repeated.

On both pages, JS files (combined into 1) are different and I am not able to detect either any JS file is creating the issue, or it is loadCSS function or Chrome (I guess it is not chrome because results on Firefox are also the same.)

**Comment by davidhellmann** [comment] 2017-02-24 08:10
Pagespeed also said it loads the css file twice. Interesting is that on my other website it's all fine. hm :) And Pagespeed said also I've blocking CSS. meh! :D

**Comment by jhabdas** [comment] 2017-03-09 18:40
Here's a workaround which may help those trying to fine-tune PageSpeed scores for modern browsers only: https://github.com/jhabdas/fetch-inject

**Comment by englishextra** [comment] 2017-03-09 18:48
Gents, stop bothering. Css/js exceeding 40 kb might be the cause. Also pretty sure the algorithm hasnt updated for long. Are you dependent on customers that require PS green results? I'm sure you dont. Double requests of CSS is not the loadCss/loadJS lib bug.

**Comment by jhabdas** [comment] 2017-03-09 18:56
Isn't the point of this library to get down to the bare metal of performance and UX? IMO it's not about the customers, it's about the users. That's why PageSpeed Insights exists.

**Comment by englishextra** [comment] 2017-03-09 19:10
@jhabdas >>That's why PageSpeed Insights exists.

It exists not for you, because you think of UX. It does for shitty SEO sites producers.

**Comment by scottjehl** [comment] 2017-03-09 19:38
Hi folks. Just a note from the maintainers. 

This project aims to produce the desired result of asynchronous CSS loading. We test in various browser dev tools to verify that it's working as expected, and we're certainly open to any fixes that improve the loading behavior. 

We've noticed inconsistent reporting from Pagespeed Insights for years with regards to whether asynchronous assets were indeed loaded that way. In cases when that particular tool throws a warning about the CSS blocking render, we have not usually been able to reproduce the problem manually. We'd love to see more consistent reporting from PSI, but we don't plan to change this script just to please the quirks of any one tool, unless it is actually a problem occurring in browsers.

Also, now that our recommended approach is to simply piggyback on `link[rel=preload]`, chrome (and I assume PSI too) will not receive any behavior from this script anyway. So, if PSI is reporting issues on a page that uses `link[rel=preload]`, it won't be a loadCSS issue.

Anyway, let's keep tracking this bug here and if you can reproduce issues for us to look at, we're always happy to look. Thanks.

**Comment by englishextra** [comment] 2017-03-09 20:24
@scottjeh Let Google Page Speed devs disclose their algorithm of testing webpages for quality optimisation. But they dont, and they wont. It's useless investment. Remember the Googles's suggestion on how to workaround css loading with animation frame, how many devs rushed on to write their own implementations of RAF, or let's remeber the AMP pages initiative which is ugly from the start...

What do I use:

my loadjs/loadcss:

```
;(function(){var loadJS=function(_src,callback){"use strict";var ref=document.getElementsByTagName("script")[0];var script=document.createElement("script");script.src=_src;script.async=true;ref.parentNode.insertBefore(script,ref);if(callback&&"function"===typeof callback){script.onload=callback;}return script;};("undefined"!==typeof window?window:this).loadJS=loadJS;}());
			;(function(){var loadCSS=function(_href,callback,media,before){"use strict";var doc=document;var ss=doc.createElement("link");var ref;if(before){ref=before;}else{var refs=(doc.body||doc.getElementsByTagName("head")[0]).childNodes;ref=refs[refs.length-1];}var sheets=doc.styleSheets;ss.rel="stylesheet";ss.href=_href;ss.media="only x";if(callback&&"function"===typeof callback){ss.onload=callback;}function ready(cb){if(doc.body){return cb();}setTimeout(function(){ready(cb);});}ready(function(){ref.parentNode.insertBefore(ss,(before?ref:ref.nextSibling));});var onloadcssdefined=function(cb){var resolvedHref=ss.href;var i=sheets.length;while(i--){if(sheets[i].href===resolvedHref){return cb();}}setTimeout(function(){onloadcssdefined(cb);});};function loadCB(){if(ss.addEventListener){ss.removeEventListener("load",loadCB);}ss.media=media||"all";}if(ss.addEventListener){ss.addEventListener("load",loadCB);}ss.onloadcssdefined=onloadcssdefined;onloadcssdefined(loadCB);return ss;};("undefined"!==typeof window?window:this).loadCSS=loadCSS;}());
```

load script that wont appear in the DOM:

```
/*!
 * Promise based script loader for the browser using script tags
 * github.com/MiguelCastillo/load-js
 * type: defaults to text/javascript
 * async: defaults to false
 * charset: defaults to utf-8
 * id: no default value
 * url: required if no text is provided
 * text: required if no url is provided
 * promiseLoadJS(["https://code.jquery.com/jquery-2.2.1.js",
 * "https://unpkg.com/react@15.3.1/dist/react.min.js"])
 * .then(function(){console.log("jQuery and react are loaded");});
 * promiseLoadJS([{async:true,url:"https://code.jquery.com/jquery-2.2.1.js"},
 * {async:true,url:"https://unpkg.com/react@15.3.1/dist/react.min.js"}])
 * .then(()=>{console.log("all done!");});
 * source: gist.github.com/pranksinatra/a4e57e586249dc3833e4
 * passes jshint
 */
;(function(){function exec(options){if("string"===typeof options){options={url:options};}if(!options.url&&!options.text){throw new Error("must provide a url or text to load");}var head=document.getElementsByTagName("head")[0]||document.documentElement;var script=document.createElement("script");script.charset=options.charset||"utf-8";script.type=options.type||"text/javascript";script.async=!!options.async;if(options.hasOwnProperty("id")){script.id=options.id;}if(options.url){script.src=options.url;return loadScript(head,script);}else{script.text=options.text;return runScript(head,script);}}function runScript(head,script){head.appendChild(script);return Promise.resolve(script);}function loadScript(head,script){return new Promise(function(resolve){var done=false;script.onload=script.onreadystatechange=function(){if(!done&&(!this.readyState||this.readyState==="loaded"||this.readyState==="complete")){done=true;script.onload=script.onreadystatechange=null;if(head&&script.parentNode){head.removeChild(script);}resolve(script);}};head.appendChild(script);});}var promiseLoadJS=function(items){return items instanceof Array?Promise.all(items.map(exec)):exec(items);};("undefined"!==typeof window?window:this).promiseLoadJS=promiseLoadJS;}());
```
load js and eval it (yeah-yeah-yeah):
```
/*!
 * Load and execute JS via AJAX
 * gist.github.com/englishextra/8dc9fe7b6ff8bdf5f9b483bf772b9e1c
 * IE 5.5+, Firefox, Opera, Chrome, Safari XHR object
 * gist.github.com/Xeoncross/7663273
 * modified callback(x.responseText,x); to callback(eval(x.responseText),x);
 * stackoverflow.com/questions/3728798/running-javascript-downloaded-with-xmlhttprequest
 * @param {String} u path string
 * @param {Object} [f] callback function
 * @param {Object} [e] on error callback function
 * ajaxLoadTriggerJS(u,f,e)
 */
;(function(){var ajaxLoadTriggerJS=function(u,f,e){var w=window,x=w.XMLHttpRequest?new XMLHttpRequest():new ActiveXObject("Microsoft.XMLHTTP");x.overrideMimeType("application/javascript;charset=utf-8");x.open("GET",u,!0);x.withCredentials=!1;x.onreadystatechange=function(){if(x.status=="404"){if(e&&"function"===typeof e){e();}console.log("Error XMLHttpRequest-ing file",x.status);return!1;}else if(x.readyState==4&&x.status==200&&x.responseText){try{var Fn=Function;new Fn(""+x.responseText).call("undefined"===typeof window?"undefined"===typeof self?"undefined"===typeof global?this:global:self:window);}catch(m){throw new Error("Error evaluating file. "+m);}if(f&&"function"===typeof f){f(x.responseText);}}};x.send(null);};("undefined"!==typeof window?window:this).ajaxLoadTriggerJS=ajaxLoadTriggerJS;}());
```

**Comment by jhabdas** [comment] 2017-03-10 05:40
Thanks for the detailed response @scottjehl. FWIW I used this library to hit PS100 for both desktop and mobile, open sourced the work and shared how to do it with Jekyll on my blog: https://habd.as/pagespeed-100-with-jekyll-s3-and-cloudfront/. Happy optimizing!

**Comment by liltinkerer** [comment] 2017-03-10 14:21
@scottjehl It's being asked over and over again, maybe you could add it to wiki/readme?

The whole discussion is absurd, the point of this small lib is to optimize user experience, not some arbitrary number that Google makes up and is often wrong, because they haven't updated their tools.

**Comment by rsteinwand** [comment] 2017-03-10 14:28
PSI just recently updated to their Blink engine, which has been in browsers for a couple years now. To say they haven't updated their tools is an understatement.

**Comment by davidhellmann** [comment] 2017-07-11 12:40
For me I fixed the problem.

This one makes two requests:
```
<link rel="preload" href="{{ cacheBuster( '/assets/css/app.min.css') }}" as="style" onload="this.rel='stylesheet'">
    <noscript>
      <link rel="stylesheet" href="{{ cacheBuster( '/assets/css/app.min.css') }}">
    </noscript>
```

this one is fine:
```

    <script>
        loadCSS("{{ cacheBuster( '/assets/css/app.min.css') }}");
      </script>
    <noscript>
        <link rel="stylesheet" href="{{ cacheBuster( '/assets/css/app.min.css') }}">
      </noscript>
```

**Comment by jhabdas** [comment] 2017-07-11 12:57
I was able to resolve the issue with a single `fetch` request and use it to load web fonts asynchronously as well [in the same call](https://github.com/jhabdas/fetch-inject#loading-non-critical-css):

```html
<style>/*! bulma.io v0.4.0 ... */</style>
<script>
fetchInject([
  '/css/non-critical.css',
  'https://cdn.jsdelivr.net/fontawesome/4.7.0/css/font-awesome.min.css'
])
</script>
```

And because it uses Fetch it works using a lower-level API than Ajax, returns a promise and supports Service Workers. Just saying.

**Comment by englishextra** [comment] 2017-07-20 14:18
@jhabdas I am afraid this library is about script tag loading - fetch is not suported by ie11 and edge13. Bsides you can't control easily if the style is loaded, and by the way you have to manipulate the re response

**Comment by jhabdas** [comment] 2017-07-20 15:06
You're a genius @englishextra. I've opened [an issue against `fetch-inject`](https://github.com/jhabdas/fetch-inject/issues/26) to help meet this end, whereby manual PE for older browsers is no longer necessary. Cheers to you for the idea.

**Comment by odahcam** [comment] 2017-11-28 10:30
Does #240 fixes this?

**Comment by scottjehl** [comment] 2017-11-28 15:31
I'm unsure if this is fixed in latest, but the issue will not occur in Chrome if you're using link[rel=preload], which is our recommended workflow now for this project. The issue is with toggle the media attribute, which will never happen in a preload-supporting browser. To test if the issue is still present for script-driven CSS loading, we can test this page I think, which calls `loadCSS()` and toggles the media attribute: https://master-origin-loadcss.fgview.com/test/test.html

**Comment by odahcam** [comment] 2017-11-28 16:14
In the version the page is using, the issue stills alive:
![image](https://user-images.githubusercontent.com/3942006/33330502-2af7b146-d446-11e7-8060-f969b6a32ac6.png)

**Comment by scottjehl** [comment] 2017-11-28 16:18
@odahcam Thanks. Still an open chrome bug. There's no plan to address this in loadCSS but we'll keep this open for info purposes.

**Comment by odahcam** [comment] 2017-11-28 20:57
We had that case of `onload=do something` where some duplicated load occours, isn't there a probabillity of this issue being triggered like that?

**Comment by scottjehl** [comment] 2017-11-28 21:00
The latest readme recommends `onload="this.onload=null; this.rel='stylesheet'"`, which makes the onload handler apply once. I think that covers what you're asking?

**Comment by odahcam** [comment] 2017-11-28 21:30
does loadCSS source code changes any attributes after the file is loaded?

**Comment by scottjehl** [comment] 2017-11-28 21:47
It doesn't change any. But it does add a `data-loadcss` attribute after polyfilling a link so that it knows not to touch the same link twice. Does that answer your question?

**Comment by web-worddoc** [comment] 2017-12-08 10:50
Have you resolved the problem regarding double request?

**Comment by odahcam** [comment] 2017-12-08 11:45
@scottjehl yes, I was thinking that maybe by changing the link element the browser could atempt to load it again.

**Comment by MartyD23** [comment] 2018-01-17 21:35
I'm also having the issue of duplicate css. Seems to happen in all browsers. GTmetrix also shows the duplicates, as does Pingdom, but WebPageTest does not show the duplicates.

**Comment by 7iomka** [comment] 2018-02-05 11:50
problem regarding double request isn't resolved

**Comment by larslevie** [comment] 2018-02-06 16:29
FWIW, I cannot reproduce this in Chrome 64.0.3282.140 (macOS) or Firefox 58.0.1 (macOS), but I **can** reproduce using Safari 11.0.3 (macOS) and Mobile Safari (iOS 11.2.2).

**Comment by ensemblebd** [comment] 2018-06-11 15:22
For me it only happened when `mediatype` was not all or screen (**print** `mediatype`). Perhaps **not** **specifying** `mediatype` leads to the same issue for all of the above cases?

Last I recall, loadCSS only replaces the `rel` and `onload` attributes. 
But if in fact it replaces `mediatype`, then that would equate to a duplicate request, especially if it's replacing the intended [or unspecified] type.

**Comment by rasenplanscher** [comment] 2019-03-10 16:16
@ensemblebd 
`loadCSS` does change the media property:
https://github.com/filamentgroup/loadCSS/blob/1b0b1054492dc48ee076af998d6bb5fc84e3a034/src/loadCSS.js#L35
https://github.com/filamentgroup/loadCSS/blob/1b0b1054492dc48ee076af998d6bb5fc84e3a034/src/loadCSS.js#L70

**Comment by ytzhakov** [comment] 2019-06-01 12:54
This still happens in June 2019.

**Closed** 2022-10-20 20:28 UTC
