### ISSUE TITLE
Callback too early

### ISSUE THREAD

**Issue by Krinkle** [filamentgroup/loadCSS#74] opened 2015-06-11 01:58 UTC
The old `onload` callback worked fine (it's called when the styles are loaded and applied). However the new `onloadCSS()` callback fires too early.

E.g. loading a stylesheet with `#foo { display: none; }` and asserting `getComputedStyle(document.getElementById('foo')).display === 'none';` fails with the `onloadCSS()` callback, but passes with the `onload` callback.

After some trial and error, I determined that this is caused by the `ss.media = "only x";` trick. While loadCSS's internal callback that changes the media value does run first, the second instance of the poller from onloadCSS() invokes the callback at a time that the styles are not yet live.

Removing the `ss.media` hack and its first callback counterpart fixes the issue.

**Comment by Krinkle** [comment] 2015-06-11 02:09
See also http://www.phpied.com/when-is-a-stylesheet-really-loaded/ for some relevant research done in 2011 by @stoyan.

**Comment by zachleat** [comment] 2015-06-11 14:04
What browser is exhibiting this behavior?

**Comment by scottjehl** [comment] 2015-06-11 14:27
Good question, @zachleat. 

Worth noting here that the `onloadCSS` extension binds directly to the `onload` event, just like it would if you use the now-deprecated callback argument. There are a few exception cases (android native browser) that don't support `onload` natively for CSS, so it attempts to patch support for those, but that's it.

One thing that might be happening here is that onload perhaps works better when bound before the link is inserted into the page. If so, that'd be a good argument for un-deprecating the callback argument and bringing the onloadCSS workaround into the core function.

**Comment by Krinkle** [comment] 2015-06-11 15:06
@zachleat wrote
> What browser is exhibiting this behavior?
Chrome latest stable.

@scottjehl wrote
> Worth noting here that the onloadCSS extension binds directly to the onload event, just like it would if you use the now-deprecated callback argument. There are a few exception cases (android native browser) that don't support onload natively for CSS, so it attempts to patch support for those, but that's it.

It does indeed use `onload` where possible. However that has no relation right now with the `media` attribute. As such it's probably firing that when the media is still set to something that doesn't apply.

Reproduction test case exposing the bug:
http://codepen.io/Krinkle/pen/qdjVJV

A fork of that pen with the `media` trick commented out – not exhibiting the bug:
http://codepen.io/Krinkle/pen/ZGyaVp

**Comment by scottjehl** [comment] 2015-06-11 15:12
Thanks @Krinkle 

One more that'd be helpful to see is the first demo with the callback argument used, and whether that indeed avoids the bug too. Easy to make?

**Comment by scottjehl** [comment] 2015-08-24 16:55
Marked for 1.0.0 milestone

**Comment by scottjehl** [comment] 2015-08-27 22:10
A couple things to try:
- toggle [rel=alternate stylesheet] or [disabled] attributes instead of messing with media, to see if they deprioritize the fetch in a similar way
- add a check for the stylesheet node's cssRules array length (just rules) in some browsers before calling defined true

**Comment by scottjehl** [comment] 2015-08-28 18:06
Updated pen with latest loadCSS. Issue persists: http://codepen.io/scottjehl/pen/MagqqJ

**Comment by scottjehl** [comment] 2015-08-28 20:30
@Krinkle 

Thanks. I think we've got this in good shape now. This PR has the edits and the codepen is working as expected with the new code. Let us know if you find any problems after the merge

**Comment by scottjehl** [comment] 2015-09-01 21:57
Notes as i'm working through this:

Our `onloadcssdefined` callback does appear to still serve as a fine onload fallback for browsers that do not support `link.onload`. Using [this test](http://codepen.io/scottjehl/full/medGXj/) (which loads a slow-loading css file to test timing), I can confirm that the onload and cssom test messages append at about the same time in the browsers we know lack onload support.

That said, our notes said that android 4.3 lacked onload support and I've found here that it does seem to support it (4.2 does not however), so we should make sure we aren't polyfilling there.

**Comment by scottjehl** [comment] 2015-09-01 22:21
Okay, progress. Here is a basic test that shows an onload handler will fire before our CSSOM check is able to flip the media type to `all`. http://codepen.io/scottjehl/pen/medGXj?editors=001

The solution will likely be to flip the media type to all using an internal onload handler of our own, in addition to the CSSOM check (whichever fires first is fine).

**Comment by scottjehl** [comment] 2015-09-01 22:29
And this test shows the workflow I think we'll want... though it's firing more often than necessary in firefox, so that may need a look. saving here for later http://codepen.io/scottjehl/pen/YyzObO?editors=001

**Comment by scottjehl** [comment] 2016-01-27 21:34
Now that we use onload to switch the media type (or a fallback if not supported), this should be fixed. Testing now!

**Comment by scottjehl** [comment] 2016-01-27 23:09
okay, I think I have a fix ready for testing. 
The new test page is the same as the original test posted in this issue, except that it uses loadCSS.js from master, and onloadCSS.js from branch 126 (which is tweaked a bit to play nicely with loadCSS's onload event handler). Also, the test's own scripting is moved to the end to work now that loadCSS is defined via an iife.

Original Failing Test: http://codepen.io/Krinkle/pen/qdjVJV
New Passing Test: http://codepen.io/scottjehl/pen/eJrBQw

Scripts involved: 
loadcss.js from master: https://github.com/filamentgroup/loadCSS/blob/126/src/loadCSS.js
onloadcss.js from branch 126: https://github.com/filamentgroup/loadCSS/blob/126/src/onloadCSS.js


If this tests out well across browsers, we'll just want to include a unit test before merging and closing out. Feedback appreciated, thanks!

**Comment by rupl** [comment] 2016-01-28 10:44
I tested both the Original and New codepens @scottjehl posted:

### Desktop

:+1: OSX Chrome 48.0.2564.82 (64-bit)
:+1: OSX Chrome Canary 50.0.2632.0 canary (64-bit)
:+1: OSX Opera 30.0.1835.59
:+1: OSX Opera 34.0.2036.50
:+1: OSX Firefox 44.0

### Mobile

:+1: iOS 9.2 (13C75) Safari
:x: iOS 9.2 (13C75) Chrome — Original failed as expected, New produced an `alert()` with "callback too early" and red section reporting same outcome:

![img_6358](https://cloud.githubusercontent.com/assets/254753/12642158/039e7268-c5ef-11e5-8ad5-d6387aa5d9b3.PNG)

**Comment by scottjehl** [comment] 2016-01-28 14:35
Thanks @rupl 
Just to clarify: are you saying the failing case was just the original test case, as expected? Thanks

**Comment by rupl** [comment] 2016-01-28 15:01
@scottjehl using the labels you provided above, both the [Original Failing Test](http://codepen.io/Krinkle/pen/qdjVJV) and [New Passing Test](http://codepen.io/scottjehl/pen/eJrBQw) failed on iOS Chrome. You can see the first couple letters of the "New Passing Test" codepen in the screenshot I provided, just to verify.

Every browser I tested failed the Original Failing Test, as expected.

**Comment by scottjehl** [comment] 2016-01-28 15:24
ah. weird ok. Will test! Thanks

**Comment by scottjehl** [comment] 2016-01-28 22:44
Thanks @rupl 

We're seeing the new test pass in iOS 9.2 in both Safari and Chrome. Same version of iOS that you noted, and we tested on two phones. Tried incognito/private mode as well in both and still got good results.

Could you tell me which version of Chrome you have? 

We're on 48.0.2564.87 here.

**Comment by scottjehl** [comment] 2016-01-28 23:07
More browser tests I just ran, all passing:
:+1: Windows 10 Edge (12)
:+1: Windows 8.1 IE 11
:+1: Windows 8 IE 10
:+1: Windows 8 Firefox 44.0
:+1: Windows 8 Chrome 47
:+1: Windows 7 IE 10
:+1: Windows 7 IE 9
:+1: Windows 7 IE 8
:+1: Windows XP IE 8
:+1: Windows XP IE 7
:+1: Windows XP IE 6
:+1: OSX Chrome 48.0.2564.82 (64-bit)
:+1: OSX Chrome Canary 50.0.2632.0 canary (64-bit)
:+1: OSX Opera 30.0.1835.59
:+1: OSX Opera 34.0.2036.50
:+1: OSX Firefox 44.0
:+1: iOS 9.2 Safari 
:+1: iOS 9.2 Chrome 
:+1: Windows Phone 8.1 (Lumia 930) IE 
:+1: Android 6 Nexus 6 Chrome 
:+1: Android 5 Galaxy s6 Chrome 
:+1: Android 4.4 Galaxy s5 Chrome 
:+1: Android 2.3 Browser

**Comment by rupl** [comment] 2016-01-29 00:10
I tested with 47.0.2526.107 — I will update the app and give it another go.

>

**Comment by rupl** [comment] 2016-01-29 00:28
Hey, what do you know! Updating Chrome caused New test to pass. I noticed
in the release notes that Chrome 48.0.2564.87 uses an entirely different
rendering engine called WKWebView.

**Comment by scottjehl** [comment] 2016-01-29 15:47
wow. Still weird to know that one didn't work though... other chrome 47s tested fine (Win 7 above, notably).

well, okay I guess! Thanks again @rupl

**Closed** 2016-01-29 16:17 UTC
Labels: Pull Requested

**Comment by abrambailey** [comment] 2016-03-10 16:31
I am using the following code to show some stuff after css has loaded:
```javascript
onloadCSS(stylesheet, function() {
    var myClasses = document.querySelectorAll('.after_css_load'),
        i = 0,
        l = myClasses.length;
    for (i; i < l; i++) {
        myClasses[i].style.display = myClasses[i].getAttribute("data-display");
    }
});
```

However, sometimes elements marked with the following are not appearing:
```html
<div class="panel-group filter-form-styles after_css_load" data-display="block" style="display:none;" id="accordionNo">
```

It seems to be a browser thing. Works intermittently in Safari Version 9.0.3 (11601.4.4) and consistently in Chrome Version 49.0.2623.87 (64-bit)
