### ISSUE TITLE
Not working on latest Firefox

### ISSUE THREAD

**Issue by neuropass** [filamentgroup/loadCSS#177] opened 2016-06-10 17:11 UTC
Hi,

it does not seem to be working with the latest firefox, same on firefox dev edition.
works fine on chrome, opera.

Also the instructions seems to be outdated? it says to include the scripts in the head tag, but than again here https://github.com/filamentgroup/loadCSS/issues/168

it says you dont need both scripts. What am I missing?

EDIT>

Well it needs the polyfill cssrelpreload.js

Can we update the readme file? How was that missed? You need 3 scripts inside the SRC folder not just two as the readme files states.

**Comment by rsteinwand** [comment] 2016-06-11 00:20
So is it working now in Firefox with the polyfill script? Because I have two websites that work just fine with Firefox or Chrome.

If it's not working, do you have a link to a page that isn't working for you?

I agree the examples could be better, it took me awhile to figure out what I needed as well.

You only need the loadCSS script if you load the style sheet with the script. That's the original way of using loadCSS. example: `loadCSS( "path/to/mystylesheet.css" );`

You need both scripts if you use the "Recommended Usage Pattern". example: `<link rel="preload" href="path/to/mystylesheet.css" as="style" onload="this.rel='stylesheet'">`

**Comment by rsteinwand** [comment] 2016-06-22 19:56
See this issue: https://github.com/filamentgroup/loadCSS/issues/180

It's possible your problem was due to the script before the stylesheets.

**Comment by larssn** [comment] 2016-08-23 10:59
I'd say its probably the last part here. You want the script to be just before the closing head tag.

**Comment by kwoxer** [comment] 2016-12-19 12:21
I have the same issue. I'm using Firefox on Ubuntu. Both are latest.

Also I'm using Firefox and also Firefox Dev. I have the same issue in both browser.

This is what my `html.tpl` looks like:
```
<script>
    /*! loadCSS: ... */
...
    /*! preoadCSS: ... */
...
  </script>
  <link rel="preload" href="/sites/all/themes/learnattack/css/main.css" as="style" onload="this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="/sites/all/themes/learnattack/css/main.css"></noscript>
  <style>
```
this works great in **Chrome**. It is loading the main.css via lazy loading. And also after a reload the `main.css` is still cached.

This issue is with **Firefox**/Dev. Here the main.css is somehow loaded 2 times but with a different size (unzipped). Here is a pic: http://i.imgur.com/7MDcpAM.png

So why is Firefox not loading the `main.css` from the Cache after the first visit? And why Firefox is loading the main.css 2 times?

This makes no sense for me because in Chrome it works perfectly well!

Thanks for any idea.

**Comment by monolux** [comment] 2017-02-01 21:30
Perhaps [this Firefox Bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1306892) is the cause for the stylesheet loading twice?

**Comment by scottjehl** [comment] 2017-02-13 22:20
Latest works well in Firefox, but does have an occasional double load issue. Tracking that here: https://github.com/filamentgroup/loadCSS/issues/189

**Closed by scottjehl** 2017-02-13 22:20 UTC
